import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Card
 * Id: a7a7ee93-b101-41fc-82b9-243be6a3a32b
 * Codename: card
 */
export type Card = IContentItem<{
  /**
   * Description (text)
   * Required: true
   * Id: 11bea77a-5906-4fa1-b698-5a7955b63fdd
   * Codename: description
   *
   * A very brief description of the user
   */
  description: Elements.TextElement;

  /**
   * Email (text)
   * Required: true
   * Id: 9a8e685d-6891-49d1-bc86-96f99b4aacbb
   * Codename: email
   *
   * The users email.
   */
  email: Elements.TextElement;

  /**
   * Emotion (text)
   * Required: true
   * Id: c6f62b64-8734-4d6a-b54b-8231bd9d200a
   * Codename: emotion
   *
   * How is this person feeling, or what are they thinking about?
   */
  emotion: Elements.TextElement;

  /**
   * Image Asset (asset)
   * Required: false
   * Id: 0aa91b54-6c7b-4419-9fda-ac44766eea6e
   * Codename: image_asset
   *
   * The user's photo. Use this OR Image URL, not both.
   */
  imageAsset: Elements.AssetsElement;

  /**
   * Image URL (text)
   * Required: false
   * Id: cd86c917-33c0-42c8-aa3c-dfc637822caf
   * Codename: imageurl
   *
   * The user's photo. Use this OR Image Asset, not both.
   */
  imageurl: Elements.TextElement;

  /**
   * Location (text)
   * Required: true
   * Id: d30a9a6b-d542-4cf2-803a-d68b06a59bfd
   * Codename: location
   *
   * The users location. City, ST (i.e. Dallas, TX)
   */
  location: Elements.TextElement;

  /**
   * Name (text)
   * Required: true
   * Id: 388e71b4-1b1b-434b-8de7-e73045635a8f
   * Codename: name
   *
   * The user's name.
   */
  name: Elements.TextElement;

  /**
   * Title (text)
   * Required: true
   * Id: e20c026a-1370-4e76-b92a-af9e6f5d2c29
   * Codename: title
   *
   * The user's job title. (e.g. CEO, Lead Developer)
   */
  title: Elements.TextElement;
}>;
