import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * CTA
 * Id: 5c1abef7-f561-42d9-ad6d-32b6668ae10c
 * Codename: cta
 */
export type CTA = IContentItem<{
  /**
   * Button href (text)
   * Required: true
   * Id: 691cf8f7-0021-46fd-9d99-0065da7deda9
   * Codename: button_href
   *
   * The URL the button will link to.
   */
  buttonHref: Elements.TextElement;

  /**
   * Button Text (text)
   * Required: false
   * Id: 31b806ac-4ef3-4636-92c9-195a3123899f
   * Codename: button_text
   *
   * The default option for button text is 'Get Started'. If you enter a value, the default will be overridden.
   */
  buttonText: Elements.TextElement;

  /**
   * Heading (text)
   * Required: true
   * Id: 8c2de276-16d1-4460-9525-6e395007580c
   * Codename: heading
   *
   * A very short heading, probably only 3-4 words.
   */
  heading: Elements.TextElement;

  /**
   * Subheading (text)
   * Required: true
   * Id: eb6ad4ab-453b-44ce-a06e-6f203c1d5f0a
   * Codename: subheading
   *
   * A slightly longer subheading, no more than 20 words.
   */
  subheading: Elements.TextElement;
}>;
