import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type FooterCategory } from './footer_category';
import { type FooterMediaLink } from './footer_media_link';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Footer
 * Id: c9e1069d-a833-4e97-88df-704f1ac5def9
 * Codename: footer
 */
export type Footer = IContentItem<{
  /**
   * Categories (modular_content)
   * Required: true
   * Id: 07a131cd-ce41-4db6-a2bc-736d2ad4efd7
   * Codename: categories
   *
   * The categories the footer will use. (About, My Account, etc)
   */
  categories: Elements.LinkedItemsElement<FooterCategory>;

  /**
   * Media Links (modular_content)
   * Required: false
   * Id: 7adc2778-2fed-44aa-8d41-ea17b447970d
   * Codename: media_links
   */
  mediaLinks: Elements.LinkedItemsElement<FooterMediaLink>;

  /**
   * Title (text)
   * Required: true
   * Id: 3d4ca7af-e7c0-4e52-9901-31ec0d7b002a
   * Codename: title
   *
   * The site the footer is for.
   */
  title: Elements.TextElement;
}>;
