import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Footer Link
 * Id: f7efbb1b-fb2a-44be-8463-a92a4303a0d5
 * Codename: footer_link
 */
export type FooterLink = IContentItem<{
  /**
   * Display Name (text)
   * Required: true
   * Id: d3fe163a-3ea5-43ca-9588-1810c35dbf25
   * Codename: display_name
   */
  displayName: Elements.TextElement;

  /**
   * Index (url_slug)
   * Required: true
   * Id: 588a477a-0638-4d2f-8ef7-8df752a1f785
   * Codename: index
   *
   * This field is auto-generated from the display name and used as an index for JSX elements in React, Vue, Next.js and the like.
   */
  index: Elements.UrlSlugElement;

  /**
   * URL (text)
   * Required: true
   * Id: 5264609c-2c57-4dc8-8334-421a310d151f
   * Codename: url
   *
   * The URL you want the link to be directed to. (e.g.  /billing  )
   */
  url: Elements.TextElement;
}>;
