import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
import { type FooterLink } from './footer_link';

/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * Footer Category
 * Id: f53c4609-4e38-4c37-97fa-fedb0b5b5938
 * Codename: footer_category
 */
export type FooterCategory = IContentItem<{
  /**
   * Links (modular_content)
   * Required: false
   * Id: 887eefa8-3302-4468-8e0e-aeffe4c6016f
   * Codename: links
   */
  links: Elements.LinkedItemsElement<FooterLink>;

  /**
   * Title (text)
   * Required: false
   * Id: 081ebd23-15c4-438a-8011-b83b1ff0f0b8
   * Codename: title
   *
   * The display name for the category.
   */
  title: Elements.TextElement;
}>;
