import { type IContentItem, type Elements } from '@kontent-ai/delivery-sdk';
/**
 * Generated by '@kontent-ai/model-generator@5.10.0'
 *
 * User Testimonial
 * Id: 4ae5c818-fc9c-4b36-9b46-42d433405088
 * Codename: testimonial
 */
export type UserTestimonial = IContentItem<{
  /**
   * Avatar (asset)
   * Required: false
   * Id: 03b2b2ac-b1d1-477a-b9bc-600241a1837d
   * Codename: avatar
   *
   * The user's avatar. If you don't have the file, use 'Avatar URL' instead and provide a url to an external file.
   */
  avatar: Elements.AssetsElement;

  /**
   * Avatar URL (text)
   * Required: false
   * Id: a5967f1e-b3c2-4875-a099-47b8ce8b2531
   * Codename: avatar_url
   *
   * Link to an external source for user avatar. Use 'Avatar' instead if you are uploading a custom image.
   */
  avatarUrl: Elements.TextElement;

  /**
   * User Name (text)
   * Required: false
   * Id: 37fe2922-effc-4d1f-b7c8-14b47dbd7352
   * Codename: user_name
   */
  userName: Elements.TextElement;

  /**
   * User Testimonial (rich_text)
   * Required: true
   * Id: 21cc9377-5fe2-417e-ae82-56cc747b15c7
   * Codename: user_testimonial
   */
  userTestimonial: Elements.RichTextElement;

  /**
   * User Tag (text)
   * Required: false
   * Id: e6b616e9-5b28-49e6-9e4c-b45b35a29d69
   * Codename: user_title
   *
   * e.g. eddiemunson (will display as @eddiemunson).
   */
  userTitle: Elements.TextElement;
}>;
